import { setupServer } from '@koi18n/next'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

setupServer({
  loader: (locale: string, id: string) =>
    import(`../locale/${locale}/${id}.json`)
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <p>Next.js example</p>
        <Suspense fallback={'Loading...'}>{children}</Suspense>
      </body>
    </html>
  )
}
